name: Security
on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]
jobs:
  Security-And-Code-Scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master
      - name: nodejsscan scan
        uses: ajinabraham/njsscan-action@master
        with:
          args: '.'
